name: chess_exercises_notes
description: "Syncronize your chess exercises books answers across your devices."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_i18n: ^0.37.1
  logger: ^2.6.2
  window_manager: ^0.5.1
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
flutter_native_splash:
  color: "#8c246f"
  image: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo_android_12.png"
    color: "#8c246f"
