name: chess_exercises_notes
description: "Syncronize your chess exercises books answers across your devices."
publish_to: "none"
version: 0.1.20+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_i18n: ^0.37.1
  logger: ^2.6.2
  window_manager: ^0.5.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flex_color_scheme: ^8.4.0
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5
  path: ^1.9.1
  yaml_edit: ^2.2.4
  diacritic: ^0.1.6
  oauth2_client: ^4.2.3
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.12.2

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 22
  adaptive_icon_background: "#8c246f"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_foreground_inset: 32
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256
flutter_native_splash:
  color: "#8c246f"
  image: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo_android_12.png"
    color: "#8c246f"
